# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
assets:
  - assets/images/

# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware 